import{a as C,S as H,i as l}from"./assets/vendor-f736e62a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const M="43225826-209ae09ba096a17ea4e8a3ec3",q="https://pixabay.com/api/";async function h(e,t){return(await C(q,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const u=document.querySelector(".gallery"),y=new H(".gallery a",{captionsData:"alt",captionDelay:250});y.refresh();function L(e){u.insertAdjacentHTML("beforeend",v(e)),y.refresh()}function v(e){return e.map(({webformatURL:t,largeImageURL:s,tags:a,likes:o,views:r,comments:n,downloads:S})=>`<li class="card">
        <a href="${s}" class="link">
          <img src="${t}" alt="${a}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${o}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${r}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${n}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${S}</p></li>
        </ul>
        </a>
      
      </li>`).join(" ")}function b(){const e=document.createElement("p");e.classList.add("end-message"),e.textContent="We're sorry, but you've reached the end of search results.",u.insertAdjacentElement("afterend",e)}const x=document.querySelector(".form"),g=document.querySelector(".search-input"),f=document.querySelector(".loader"),p=document.querySelector(".load-more-btn");f.style.display="none";let c="",i=1;const m=15;x.addEventListener("submit",P);async function P(e){if(e.preventDefault(),c=g.value.trim(),i=1,u.innerHTML="",c===""){l.error({message:"The field can not be empty!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",messageSize:"16px",messageLineHeight:"100%",iconColor:"white",title:"Attention"}),d();return}I(),w();try{const t=await h(c,i,m),s=t.totalHits;if(t.hits.length===0){u.innerHTML="",l.info({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",messageSize:"16px",messageLineHeight:"100%",iconColor:"white",title:"Info"}),d();return}else L(t.hits),g.value="",T();m*i>=s&&(d(),b())}catch(t){console.error("Error:",t),l.error({message:"Failed to fetch images. Please try again later.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",messageSize:"16px",messageLineHeight:"100%",iconColor:"white",title:"Error"})}finally{E()}}p.addEventListener("click",async()=>{try{i+=1;const e=await h(c,i,m),t=e.totalHits;L(e.hits),w(),m*i>=t&&(d(),b()),$()}catch(e){console.error("Error fetching more images:",e),l.error({title:"Error",message:`Error fetching more images: ${e}`,position:"topRight"})}finally{E()}});function $(){const e=document.querySelector(".gallery a");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}function w(){f.style.display="block"}function E(){f.style.display="none"}function T(){p.style.display="block"}function d(){p.style.display="none"}function I(){const e=document.querySelector(".end-message");e&&e.remove()}
//# sourceMappingURL=commonHelpers.js.map
